/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package css475.dropstudents.ecis.admin;

import css475.dropstudents.ecis.MySqlConnection;
import java.awt.Dimension;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joelm
 */
public class InsertFrame extends PromptDialog<String> {

    public final String tableName;
    private MySqlConnection.Database db;
    private final ColumnSpec[] spec;
    private ColumnSpecPanel[] inputs;
    /**
     * Creates new form InsertFrame
     */
    public InsertFrame(MySqlConnection.Database db, String tableName, ColumnSpec... inputs) {
        this.tableName = tableName;
        this.db = db;
        this.spec = inputs;
        initComponents();
        setTitle(String.format("New %s", tableName));
        int preferredWidth = getPreferredSize().width;
        int totalHeight = 40 + submitButton.getHeight();
        List<ColumnSpecPanel> inputsList = new ArrayList();
        for (ColumnSpec spec : inputs) {
            ColumnSpecPanel input = new ColumnSpecPanel(db, spec);
            input.setPreferredSize(new Dimension(preferredWidth, 24));
            totalHeight += 30;
            inputsPanel.add(input);
            inputsList.add(input);
            System.out.println(String.format("Added spec to frame: %s (%s) -> %s", spec.name, spec.type.name(), Objects.toString(input)));
        }
        this.inputs = inputsList.toArray(new ColumnSpecPanel[0]);
        setPreferredSize(new Dimension(preferredWidth, totalHeight));
        pack();
    }
    
    public String getInsertQuery() {
        return String.format("INSERT INTO `%s` (%s) VALUES (%s);", 
                this.tableName,
                Arrays.stream(spec)
                        .map(ColumnSpec::getName)
                        .collect(Collectors.joining(", ")),
                Arrays.stream(inputs)
                        .map(ColumnSpecPanel::getValue)
                        .collect(Collectors.joining(", "))
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputsPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 140));

        inputsPanel.setLayout(new javax.swing.BoxLayout(inputsPanel, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(inputsPanel, java.awt.BorderLayout.CENTER);

        submitButton.setText("INSERT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            if (db.execute(getInsertQuery()) > 0)
                submit(); // confirm and close prompt
        } catch (SQLException ex) {
            Logger.getLogger(InsertFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); // show error message
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    @Override
    public String getResult() {
        return getInsertQuery();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inputsPanel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
